export enum StatusOrder {
  ACEITO = 'ACEITO',
  PENDENTE = 'PENDENTE',
  PREPARANDO = 'PREPARANDO',
  ENTREGUE = 'ENTREGUE',
  CANCELADO = 'CANCELADO',
  CONFIRMADO_CLIENTE = 'CONFIRMADO_CLIENTE',
}
