/* eslint-disable @next/next/no-sync-scripts */
import '../../theme/globals.css';
import type { Metadata } from 'next';
import { SomeChildrenInterface } from '@/utils/types/generics/layout.type';
import { SessionProvider } from '@/providers/sessionProvider';
import { LoadingProvider } from '@/providers/loadingProvider/loadingProvider';
import { Toaster } from 'react-hot-toast';
import { Provider } from '@/components/ui/provider';
import { AuthProvider } from '@/providers/authProvider';
import { CartProvider } from '@/providers/cartProvider/cartProvider';

//import { AuthProvider } from '@/providers/refresh';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: SomeChildrenInterface) {
  return (
    <html lang="pt-br">
      <body
        suppressHydrationWarning={true}
        className="flex min-h-screen flex-col antialiased"
      >
        <SessionProvider>
          <AuthProvider>
            <LoadingProvider>
              <CartProvider>
                <Provider>
                  <main className="flex-grow">{children}</main>
                </Provider>
              </CartProvider>
            </LoadingProvider>
          </AuthProvider>
        </SessionProvider>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
