import '../../theme/globals.css';
import type { Metadata } from 'next';
import { SomeChildrenInterface } from '@/utils/types/generics/layout.type';
import { SessionProvider } from '@/providers/sessionProvider';
import { LoadingProvider } from '@/providers/loadingProvider/loadingProvider';
import { Toaster } from 'react-hot-toast';
import { Provider } from '@/components/ui/provider';
import { CartProvider } from '@/providers/cartContext/cartProvider';
import { Header } from '@/components/Header/Header';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/libs/auth';
import { Footer } from '@/components/Footer/Footer';

//import { AuthProvider } from '@/providers/refresh';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: SomeChildrenInterface) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="pt-br">
      <body
        suppressHydrationWarning={true}
        className="flex min-h-screen flex-col antialiased"
      >
        <SessionProvider>
          <LoadingProvider>
            {/* <SessionWatcher /> */}
            <CartProvider>
              <Provider>
                <Header session={session} />
                <main className="flex-grow">{children}</main>
                <Footer />
              </Provider>
            </CartProvider>
          </LoadingProvider>
        </SessionProvider>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
